### ISSUE TITLE
rake db:migrate fails

### ISSUE THREAD

**Issue by emiltin** [emiltin/poolparty_example#1]
root@domU-12-31-38-00-40-57:/var/www/my_app/releases/20090501093415# RAILS_ENV=production rake db:migrate --trace
(in /var/www/my_app/releases/20090501093415)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
*\* Invoke db:schema:dump (first_time)
*\* Invoke environment 
*\* Execute db:schema:dump
rake aborted!
undefined method `reenable' for <Rake::Task db:schema:dump => [environment]>:Rake::Task
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/tasks/databases.rake:253
/usr/lib/ruby/1.8/rake.rb:546:in`call'
/usr/lib/ruby/1.8/rake.rb:546:in `execute'
/usr/lib/ruby/1.8/rake.rb:541:in`each'
/usr/lib/ruby/1.8/rake.rb:541:in `execute'
/usr/lib/ruby/1.8/rake.rb:508:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:501:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:501:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:494:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/tasks/databases.rake:117
/usr/lib/ruby/1.8/rake.rb:546:in`call'
/usr/lib/ruby/1.8/rake.rb:546:in `execute'
/usr/lib/ruby/1.8/rake.rb:541:in`each'
/usr/lib/ruby/1.8/rake.rb:541:in `execute'
/usr/lib/ruby/1.8/rake.rb:508:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:501:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:501:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:494:in `invoke'
/usr/lib/ruby/1.8/rake.rb:1931:in`invoke_task'
/usr/lib/ruby/1.8/rake.rb:1909:in `top_level'
/usr/lib/ruby/1.8/rake.rb:1909:in`each'
/usr/lib/ruby/1.8/rake.rb:1909:in `top_level'
/usr/lib/ruby/1.8/rake.rb:1948:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1903:in `top_level'
/usr/lib/ruby/1.8/rake.rb:1881:in`run'
/usr/lib/ruby/1.8/rake.rb:1948:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1878:in`run'
/usr/bin/rake:31

**Comment by emiltin** [comment]
outdated
